version: 2.2.2.{build}
image: Visual Studio 2017
configuration: Release
shallow_clone: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  project_feed: true
before_build:
- cmd: nuget restore C:\Projects\Pathfindax\Source\Code
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
artifacts:
- path: Source\Code\Binaries\Release\Pathfindax.dll
  name: Pathfindax.dll
- path: Source\Code\Binaries\Release\Duality.Plugins.Pathfindax.core.dll
  name: Pathfindax.Duality.core.dll
- path: Source\Code\Binaries\Release\Duality.Plugins.Pathfindax.Tilemaps.core.dll
  name: Pathfindax.Duality.Tilemaps.dll
deploy:
- provider: NuGet
  api_key:
    secure: AmEmyZ6/NdCfuHypu7kSrG8Yijc+S9ON/1BtLxBdYmoaCvJD1NXDGFYG74nW5Ka5
  on:
    APPVEYOR_REPO_TAG: true