image: Visual Studio 2017
configuration: z_CI_config
build_script:
- ps: Invoke-Expression .\CI_script.ps1 
artifacts:
- path: 'Artifacts\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: AmEmyZ6/NdCfuHypu7kSrG8Yijc+S9ON/1BtLxBdYmoaCvJD1NXDGFYG74nW5Ka5
  on:
    branch: /^(develop)$/